config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'repositories#index'
  resources :users
  resources :repositories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
class Repository < ApplicationRecord
  validates :name, presence: true

  has_many :repository_users
  has_many :users, through: :repository_users

  scope :search_by_name_or_description, ->(query) {
    where("name ILIKE :query OR description ILIKE :query", query: "%#{query}%")
  }
end

app/models/repository_user.rb
class RepositoryUser < ApplicationRecord
  belongs_to :user
  belongs_to :repository
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  has_many :repository_users
  has_many :repositories, through: :repository_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @repositories = Repository.search_by_name_or_description(params[:search])
    else
      @repositories = Repository.all
    end
  end


  def show
  end

  def new
    @repository = Repository.new
    @repository.users.build  # Build a new user associated with the repository
  end

  def create
    @repository = Repository.new(repository_params)

    if @repository.save
      redirect_to @repository, notice: 'Repository was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @repository.update(repository_params)
      redirect_to @repository, notice: 'Repository was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @repository.destroy
    redirect_to repositories_url, notice: 'Repository was successfully destroyed.'
  end

  private

  def set_repository
    @repository = Repository.includes(:users).find(params[:id])
  end

  def repository_params
    params.require(:repository).permit(:name, users_attributes: [:id, :name, :email])
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleWebApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/edit.html.erb
<h1>Edit Repository</h1>
<%= simple_form_for(@repository) do |f| %>
  <%= f.input :name %>

  <!-- Fields for users -->
  <%= f.simple_fields_for :users do |user_fields| %>
    <%= user_fields.input :name, label: "User Name" %>
    <%= user_fields.input :email, label: "User Email" %>
  <% end %>

  <%= f.button :submit %>
<% end %>
<br>
<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Repositories</h1>

<%= form_tag repositories_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search repositories by name or description" %>
  <%= submit_tag "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User name</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= link_to repository.name, repository %></td>
        <td><%= repository.description %></td>
        <td>
          <% repository.users.each do |user| %>
            <%= user.first_name + '' + user.last_name %><br>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
        <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>
<%= simple_form_for(@repository) do |f| %>
  <%= f.input :name %>

  <%= f.simple_fields_for :users do |user_fields| %>
    <%= user_fields.input :first_name, label: "First Name" %>
    <%= user_fields.input :last_name, label: "Last Name" %>
    <%= user_fields.input :email, label: "User Email" %>
  <% end %>

  <%= f.button :submit %>
<% end %>
<br>
<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>
<br>
<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>User List</h1>

<% @users.each do |user| %>
  <p><%= user.first_name %> <%= user.last_name %> - <%= user.email %></p>
  <%= link_to 'Show', user_path(user) %> |
  <%= link_to 'Edit', edit_user_path(user) %> |
  <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User Details</h1>

<p><strong>First Name:</strong> <%= @user.first_name %></p>
<p><strong>Last Name:</strong> <%= @user.last_name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>